DROP TABLE IF EXISTS TRADE_INFORMATION;
  
CREATE TABLE TRADE_INFORMATION (
    
  TRADINGID VARCHAR(250),
  VERSION INT,
  BOOKID VARCHAR(250),
  COUNTER_PARTY_ID VARCHAR(250),
  MATURITY_DATE DATE,
  CREATED_DATE DATE,
  EXPIRED VARCHAR(250),
  PRIMARY KEY (TRADINGID, VERSION)
);